name: rl4mg
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_0
  - openssl=1.0.2p=h1de35cc_0
  - pip=10.0.1=py36_0
  - python=3.6.6=hc167b69_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.2.0=py36_0
  - sqlite=3.24.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - bleach==2.1.4
    - cycler==0.10.0
    - decorator==4.3.0
    - defusedxml==0.5.0
    - entrypoints==0.2.3
    - future==0.16.0
    - html5lib==1.0.1
    - ipykernel==5.0.0
    - ipython==6.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.12.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - markupsafe==1.0
    - matplotlib==3.0.0
    - mistune==0.8.3
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - notebook==5.7.0
    - numpy==1.15.1
    - pandocfilters==1.4.2
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.2.0
    - prometheus-client==0.3.1
    - prompt-toolkit==1.0.15
    - ptyprocess==0.6.0
    - pygments==2.2.0
    - pyparsing==2.2.2
    - python-dateutil==2.7.3
    - pyzmq==17.1.2
    - qtconsole==4.4.1
    - scipy==1.1.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - six==1.11.0
    - style==1.1.0
    - terminado==0.8.1
    - testpath==0.4.1
    - torch==0.4.1
    - torchvision==0.2.1
    - tornado==5.1.1
    - tqdm==4.26.0
    - traitlets==4.3.2
    - update==0.0.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
prefix: /Users/benjamingenchel/anaconda/envs/rl4mg

